### ISSUE TITLE
5 weapon proficiencies?

### ISSUE THREAD

**Issue by ChitownWillie** [Skitia/Kale-BG1#3]
Just curious if it was intentional for him to have 5 weapon proficiencies, including 2* in "Sword & Shield".

Thanks.

p.s. Really enjoying the mod; sound set is a lot of fun.

**Comment by Skitia** [comment]
I checked, my local version only has four:

[image: image.png]
I pulled from the github version and that also has four. The above is the
intended proficiency spread.

Where are the five proficiencies in the version you have?

**Comment by ChitownWillie** [comment]
- Long Sword : 1
- Two-Handed Sword: 1
- Sling: 1
- Sword & Shield: 2

(Looks like your "image.png" doesn't appear - What was he intended to have?)

I'm wondering if "Scales of Balance" somehow messed around with it:

Mods affecting X3KALE.CRE:
00000: /* created or unbiffed */ KALE/KALE.TP2~ 0 0 // Kale NPC for BG1EE and SoD1.67
00001:  KALE/KALE.TP2~ 0 1 // Give Kale the Warden Class? (Recommended)Warden(Fighter Kit)1.67
00002:  MIGHT_AND_GUILE/MIGHT_AND_GUILE.TP2~ 0 245 // Revised Movement Bonuses (Quickstride)4.19
00003:  CDTWEAKS/SETUP-CDTWEAKS.TP2~ 0 2020 // Two-Handed Bastard Swordsv14
00004:  CDTWEAKS/SETUP-CDTWEAKS.TP2~ 0 3330 // Make Party Members Less Likely to Die Irreversiblyv14
00005:  SCALES_OF_BALANCE/SCALES_OF_BALANCE.TP2~ 0 121 // WPO - Weapon Category Collapsev5.38.1
00006:  SCALES_OF_BALANCE/SCALES_OF_BALANCE.TP2~ 0 206 // SBO - Hit Dice OverhaulGenerous (above-average) hit pointsv5.38.1
00007:  STRATAGEMS/SETUP-STRATAGEMS.TP2~ 0 5900 // Initialise AI components (required for all tactical and AI components)34.3
00008:  TNT/TNT.TP2~ 0 59 // Fair fightsAlso remove undroppable items granting unfair advantages from all enemies | POWER USER component, consult readmev8.19
00009:  EE_COSMETIC_ENHANCEMENTS/EE_COSMETIC_ENHANCEMENTS.TP2~ 0 22 // Improved slime-type monster animationsv1.0.0

**Comment by Skitia** [comment]
I'm guessing it's your two handed bastard swords mod. Kale has a
proficiency in bastard sword, my bet is the mod is changing him so he has
one in long sword and one in two handed sword to make bastard swords
functional as two handed weapons.

**Comment by ChitownWillie** [comment]
Thanks Tinkerbell.

So were the original proficiencies for the Warden version?

   - 1* Bastard Swords
   - 1* Slings
   - 2* Sword & Shield

**Comment by Skitia** [comment]
Correct! :)

**Comment by ChitownWillie** [comment]
Turns out the following tweak was splitting Kale's "Bastard Sword" proficiency into "Long Sword" + "Two-Handed Sword".

00003: CDTWEAKS/SETUP-CDTWEAKS.TP2~ 0 2020 // Two-Handed Bastard Swordsv14
